### PR TITLE
Feature: User Can Create Social Feed Post

### PR DESCRIPTION
**Pull request by EJamesssss**
Guys pareview thanks!

### CODE REVIEW

**Comment by superspike7** [comment]
pa change pala ng PR title para consistent
like: Feature: User Social Feed Post or something

**Review by superspike7 — COMMENTED** [review]
next time we'll use `git rebase main` instead of `git merge main` 
actually this was my bad for not addressing this early

**Review by superspike7 — CHANGES_REQUESTED** [review]
pa change ng commit message if working na yung WIP
then also try to follow the commit message pattern "verb" + "noun"
like `add user post creation`

**Comment by reyolan** [comment]
Logic about Post looks good to me.

Alternatively, `redirect_back(fallback_location: any_url)` can be switched to: `redirect_back_or_to any_url`
It's only a syntactic sugar in Rails 7 but doesn't really matter if you prefer using redirect_back syntax since it is used in Rails 6.

**Review by reyolan — COMMENTED** [review]
Logic about Post looks good to me.

Alternatively, `redirect_back(fallback_location: any_url)` can be switched to: `redirect_back_or_to any_url`
It's only a syntactic sugar in Rails 7 but doesn't really matter if you prefer using redirect_back syntax since it is used in Rails 6.

-- Below will just be a minor comment for cleaner code.

In your routes.rb:
`resources :destroy_attachments, only: [:destroy]`

destroy_attachments resource only has a single action, so alternatively, you can just remove the brackets.

`resources :destroy_attachments, only: :destroy`

Only supply an array if there will be 2 or more actions in a particular resource.

Nonetheless, good job!

**Pull request merged**
