### PR TITLE
Feature: Message (Unread count) and Comment Notifications

### LINKED ISSUE #22: FEATURE: Message and Comment Notifications
Trigger Notifications when the user have:
- [x] Unread Messages
- [x] A post where a particular user commented.
- [x] Real time update of notification count
- [x] Apply Notification Static UI

### PR DESCRIPTION
**Pull request by reyolan**
closes #22 

- Still has bugs (display bugs)
- There may be styles that needed to be changed due to the restrictions in broadcasting via TurboStream (let's talk about it later)
- Check the files thoroughly when there are conflicts, medyo fragile yung nagawa kong code. If there is still extra time after finishing MVP, will refactor my code. Fragile dahil sa restrictions ng broadcasting through TurboStream (sobrang daming workarounds na need gawin)

### CODE REVIEW

**Comment by reyolan** [comment]
- Biglang may naisip lang ako na temporary fix for issue in turbostream

**Comment by reyolan** [comment]
I tried but badly failed hahahha. I will revisit the bug if there is still enough time after finishing the MVP.

**Comment by reyolan** [comment]
Will close again, sorry very indecisive, may naisip ulit akong solution hehe, will just rest a bit

**Comment by reyolan** [comment]
Alaws talaga hahahhahahahahaha! Goods naman sya, display bug lang talaga in real time, nakaka OC kasi

**Review by superspike7 — APPROVED** [review]
grabe galling galling

**Pull request merged**
